<?php

/**
 * MIT License
 * Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
 */

namespace SprykerEco\Shared\FactFinderSdk;

interface FactFinderSdkConstants
{
    const ENVIRONMENT = 'FACTFINDERSDK:ENVIRONMENT';
    const ENVIRONMENT_PRODUCTION = 'FACTFINDERSDK:ENVIRONMENT_PRODUCTION';
    const ENVIRONMENT_DEVELOPMENT = 'FACTFINDERSDK:ENVIRONMENT_DEVELOPMENT';
    const ENVIRONMENT_TEST = 'FACTFINDERSDK:ENVIRONMENT_TEST';
    const CSV_DIRECTORY = 'FACTFINDERSDK:CSV_DIRECTORY';
    const EXPORT_QUERY_LIMIT = 'FACTFINDERSDK:EXPORT_QUERY_LIMIT';
    const EXPORT_FILE_NAME_PREFIX = 'FACTFINDERSDK:EXPORT_FILE_NAME_PREFIX';
    const EXPORT_FILE_NAME_DELIMITER = 'FACTFINDERSDK:EXPORT_FILE_NAME_DELIMITER';
    const EXPORT_FILE_EXTENSION = 'FACTFINDERSDK:EXPORT_FILE_EXTENSION';
    const PHP_LOGGER_CONFIG_PATH = 'FACTFINDERSDK:PHP_LOGGER_CONFIG_PATH';
    const DETAIL_PAGE_URL = 'FACTFINDERSDK:DETAIL_PAGE_URL';
    const CHANNEL_PREFIX = 'FACTFINDERSDK:CHANNEL_PREFIX';
    const DEFAULT_PRODUCTS_PER_PAGE = 'FACTFINDERSDK:DEFAULT_PRODUCTS_PER_PAGE';
    const ITEM_FIELDS = 'FACTFINDERSDK:ITEM_FIELDS';
    const CATEGORIES_MAX_COUNT = 'FACTFINDERSDK:CATEGORIES_MAX_COUNT';
    const ADMIN_PANEL_URL = 'FACTFINDERSDK:ADMIN_PANEL_URL';
}
